CREATE TABLE IF NOT EXISTS /*_*/loop_literature_items (
  `lit_itemtype` varchar(255) NOT NULL,
  `lit_itemkey` varchar(255) NOT NULL,
  `lit_address` varchar(255) NOT NULL,
  `lit_author` varchar(255) NOT NULL,
  `lit_booktitle` varchar(255) NOT NULL,
  `lit_chapter` int(10) NOT NULL,
  `lit_edition` int(10) NOT NULL,
  `lit_editor` varchar(255) NOT NULL,
  `lit_howpublished` varchar(255) NOT NULL,
  `lit_institution` varchar(255) NOT NULL,
  `lit_isbn` bigint(10) NOT NULL,
  `lit_journal` varchar(255) NOT NULL,
  `lit_month` varchar(255) NOT NULL,
  `lit_note` varchar(255) NOT NULL,
  `lit_number` int(10) NOT NULL,
  `lit_organization` varchar(255) NOT NULL,
  `lit_pages` varchar(255) NOT NULL,
  `lit_publisher` varchar(255) NOT NULL,
  `lit_school` varchar(255) NOT NULL,
  `lit_series` varchar(255) NOT NULL,
  `lit_title` varchar(255) NOT NULL,
  `lit_type` varchar(255) NOT NULL,
  `lit_url` varchar(255) NOT NULL,
  `lit_volume` varchar(255) NOT NULL,
  `lit_year` int(10) NOT NULL,
  PRIMARY KEY (lit_itemkey)
) /*$wgDBTableOptions*/;