CREATE TABLE IF NOT EXISTS /*_*/loop_settings (
  `lset_id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `lset_timestamp` TIMESTAMP NOT NULL,
  `lset_imprintlink` varbinary(255) NOT NULL,
  `lset_privacylink` varbinary(255) NOT NULL,
  `lset_oncampuslink` varbinary(255) NOT NULL,
  `lset_rightstext` varbinary(255) NOT NULL,
  `lset_rightstype` varbinary(255) NOT NULL,
  `lset_rightsurl` varbinary(255) NOT NULL,
  `lset_rightsicon` varbinary(255) NOT NULL,
  `lset_customlogo` varbinary(255) NOT NULL,
  `lset_customlogofilename` varbinary(255) NOT NULL,
  `lset_customlogofilepath` varbinary(255) NOT NULL,
  `lset_languagecode` varbinary(255) NOT NULL,
	`lset_extrafooter` varbinary(255) NOT NULL,
	`lset_extrafooterwikitext` varbinary(255) NOT NULL,
	`lset_extrafooterparsed` varbinary(255) NOT NULL,
  `lset_socialfbicon` varbinary(255) NOT NULL,
  `lset_socialfblink` varbinary(255) NOT NULL,
  `lset_socialtwicon` varbinary(255) NOT NULL,
  `lset_socialtwlink` varbinary(255) NOT NULL,
  `lset_socialyticon` varbinary(255) NOT NULL,
  `lset_socialytlink` varbinary(255) NOT NULL,
  `lset_socialghicon` varbinary(255) NOT NULL,
  `lset_socialghlink` varbinary(255) NOT NULL,
  `lset_socialinicon` varbinary(255) NOT NULL,
  `lset_socialinlink` varbinary(255) NOT NULL,
  `lset_skinstyle` varbinary(255) NOT NULL,
  PRIMARY KEY (lset_id)
) /*$wgDBTableOptions*/;