<?php 

class LoopScreenshot {
	
	public static function onParserSetup( Parser $parser ) {
		$parser->setHook( 'loop_screenshot', 'LoopScreenshot::renderLoopScreenshot' );
		return true;
	}	
	
	public static function onParserAfterTidy( &$parser, &$text ) {

		$matches = array();
		preg_match_all( '/(<div class="loop_screenshot_begin" id=")(\w*)(">)(.*)(<\/div><div class="loop_screenshot_end"><\/div>)/ius', $text, $matches );
		$articleId = $parser->getTitle()->getArticleID();
		if ( $matches) {
			$c = count( $matches[0] ); 
			
			for ( $i = 0; $i < $c; $i++ ) {
				$png = LoopScreenshot::html2png( $matches[4][$i], $matches[2][$i], $articleId );
			}
			
		}

		return true;
	}	
	
	public static function renderLoopScreenshot( $input, array $args, $parser, $frame ) {
		
		$return = '<div class="loop_screenshot_begin" id="'.$args['id'].'">';
		$return .= $parser->recursiveTagParseFully( $input );
		$return .= '</div><div class="loop_screenshot_end"></div>';		
		
		return $return;

	}
		
	public static function html2png ( $content, $id, $articleId ) {

		global $wgScreenshotUrl, $wgUploadDirectory, $wgCanonicalServer;
		
		if ( !empty ( $wgScreenshotUrl ) ) {

			$skin = new SkinLoop();
			ob_start();
			$skin->outputPage();
			$html = ob_get_contents();
			ob_end_clean();

			$doc = new DOMDocument();
			$doc->loadHtml($html);

			#get stylesheet link generated by skin
			$linkedUrls = array();
			$linkElements = $doc->getElementsByTagName( 'link' );
			if ( $linkElements ) {
				foreach( $linkElements as $link ) {
					$tmpHref = $link->getAttribute( 'href' );
					if( strpos( $tmpHref, 'load.php' ) !== false ) {
						$linkedUrls[] = $tmpHref;
					}
				}
			}

			$html = '<!DOCTYPE html>';
			$html .= '<html>';
			$html .= '<head>';
			$html .= '<meta charset="UTF-8" />';
			foreach ( $linkedUrls as $url ) {
				$html .= '<link rel="stylesheet" href="' . $wgCanonicalServer . $url . '">';
			}	
			$html .= '</head>';
			$html .= '<body>' . $content . '</body></html>';

			$screenshotDir = $wgUploadDirectory.'/screenshots';
			if ( !is_dir( $screenshotDir ) ) {
				@mkdir( $screenshotDir, 0775, true );
			}
			$screenshotPageDir = $screenshotDir.'/'.$articleId;
			if ( !is_dir( $screenshotPageDir ) ) {
				@mkdir( $screenshotPageDir, 0775, true );
			}
			
			$screenshotHtmlFile = $screenshotPageDir.'/'.$id.'.html';
			$screenshotPngFile = $screenshotPageDir.'/'.$id.'.png';
			
			$fh = fopen( $screenshotHtmlFile, 'w+' );
			fwrite ( $fh, $html );
			fclose( $fh );
			$ch = curl_init();
			curl_setopt ( $ch, CURLOPT_POST, true );
			curl_setopt ( $ch, CURLOPT_URL, ( $wgScreenshotUrl ) );
			curl_setopt ( $ch, CURLOPT_POSTFIELDS, "url=".$screenshotHtmlFile );
			curl_setopt ( $ch, CURLOPT_RETURNTRANSFER, true );
			$imageContent = curl_exec( $ch );
			curl_close( $ch );

			if ( !empty( $imageContent ) ) {
				$fh = fopen( $screenshotPngFile, 'w+' );
				fwrite ( $fh, $imageContent );
				fclose( $fh );
			}
			unset( $screenshotHtmlFile );
			#dd($image_content);
		}

		return true;
	}
}

?>